#Ui msg config
formapp:
  message:
    regSucces: Registration Successful-dev
    regFailure: Registration Failure
    
#connection pool config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: tiger
   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
